"""gotime: multi-provider driving directions and real-time traffic collector.

Public surface:
    - :data:`__version__` - package version string, injected at build time by
      ``hatch-vcs`` from the matching git tag. Development checkouts fall back
      to ``0.0.0+dev``.
    - :class:`TripResult` - normalized result returned by every provider.
    - :class:`BaseProvider` - protocol/ABC for provider adapters.
    - :func:`query_providers` - high-level convenience for multi-provider queries.
    - :func:`configure_logging` - idempotent logger setup with secret redaction.
"""

from gotime.logging import configure_logging, get_logger
from gotime.models import TripResult, Waypoint
from gotime.providers.base import BaseProvider, ProviderError, VerificationResult
from gotime.providers.registry import available_providers, get_provider
from gotime.services.query import persist_trip, query_providers
from gotime.services.verify import verify_keys

try:  # generated by hatch-vcs at build time
    from gotime._version import __version__
except ImportError:  # pragma: no cover - only hit in unbuilt source checkouts
    __version__ = "0.0.0+dev"

__all__ = [
    "__version__",
    "TripResult",
    "Waypoint",
    "BaseProvider",
    "ProviderError",
    "VerificationResult",
    "available_providers",
    "get_provider",
    "query_providers",
    "persist_trip",
    "verify_keys",
    "configure_logging",
    "get_logger",
]
